- name: Provisioning
  hosts: all
  vars:
    env: test
  tasks:
    - name: install hello service systemd unit file
      become: true
      template:
        src: /home/vagrant/hello.service.j2
        dest: /etc/systemd/system/hello.service
    - name: Start hello service
      become: true
      systemd:
        state: started
        name: hello
